In [ ]:
import numpy as np


In [ ]:
years_experience_required = np.array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
#increasing years of experience by 1

In [ ]:
years_experience_required_plus_one = years_experience_required + 1

In [ ]:
years_experience_required_plus_one

array([2, 3, 4, 5, 6, 7, 8])

In [ ]:
years_experience_required_minus_one = years_experience_required - 1

In [ ]:
years_experience_required_minus_one

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
years_experince_by_half = years_experience_required / 2

In [ ]:
years_experince_by_half

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5])

In [ ]:
years_experince_double = years_experience_required * 2
years_experince_double

array([ 2,  4,  6,  8, 10, 12, 14])

In [ ]:
# sciling

# sciling out the years of experince required for second and third job postings

years_experience_required_second_third = years_experience_required[1:6:2] # indexing is similar to list, [start:stop:step], start: inlcuisve, stop:exclusive and step:not mandatory
years_experience_required_second_third

array([2, 4, 6])

In [ ]:
#Boolean Indexing

years_experience_required_more_than_two = years_experience_required[years_experience_required > 2]
years_experience_required_more_than_two

array([3, 4, 5, 6, 7])

In [ ]:
range(10)

range(0, 10)

In [ ]:
my_list = list(range(10))

In [ ]:
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
import random

salary_random = random.randint(100000,150000)

In [ ]:
salary_random

108121

In [ ]:
import random

salary_random = [random.randint(10,15) for x in range(10)]

In [ ]:
salary_random

[10, 12, 11, 12, 15, 14, 15, 15, 13, 15]

In [ ]:
salary_array = np.array(salary_random)

In [ ]:
salary_array

array([10, 12, 11, 12, 15, 14, 15, 15, 13, 15])

In [ ]:
sum(salary_array)

np.int64(132)

In [ ]:
int(np.prod(salary_array))

145945800000

In [ ]:
np.cumprod(salary_array)

array([          10,          120,         1320,        15840,
             237600,      3326400,     49896000,    748440000,
         9729720000, 145945800000])

In [ ]:
np.cumsum(salary_array)

array([ 10,  22,  33,  45,  60,  74,  89, 104, 117, 132])

In [ ]:
np.std(salary_array,ddof=1)

np.float64(1.873795909674026)

In [ ]:
salary_array

array([10, 12, 11, 12, 15, 14, 15, 15, 13, 15])

In [ ]:
revised_salary_array = np.where(salary_array <12,12,salary_array) # simialr to if statement if the condition is correct it returns 12, else returs the actual value in salary array

In [ ]:
revised_salary_array

array([12, 12, 12, 12, 15, 14, 15, 15, 13, 15])

In [ ]:
for x in salary_array:
  print(x)

10
12
11
12
15
14
15
15
13
15


In [ ]:
len(salary_array)

10

In [ ]:
salary_array.size

10

In [ ]:
noise = np.random.normal(0,1,len(salary_array))